export const advantageTabs = {
  advantage: [
    "Revenue",
    "Net income",
    "EBIT",
    "EBITDA",
    "Gross Margin",
    "Net Profit Margin",
    "Operating Margin",
    "Earnings quality",
    "Multichart",
    "Custom",
  ],
  foresight: [
    "Assets",
    "Cash",
    "Equity",
    "Debt",
    "Debt / Equity ratio",
    "Current Ratio",
    "CFO / Debt",
    "Multichart",
    "Custom",
  ],
  efficiency: [
    "ROE",
    "ROIC",
    "ROA",
    "Fin Leverage ",
    "Multichart",
    "Custom",
  ],
  stability: [
    "Growth rate (q/q)",
    "Average G 8 q",
    "Average G 20 q",
    "SD 8 q",
    "SD 20 q",
    "Multichart",
    "Custom",
  ],
  multipliers: [
    "Assets",
    "Cash",
    "Equity",
    "Debt",
    "Debt / Equity ratio",
    "Current Ratio",
    "CFO / Debt",
    "Multichart",
    "Custom",
  ],
  other: [
    "Assets",
    "Cash",
    "Equity",
    "Debt",
    "Debt / Equity ratio",
    "Current Ratio",
    "CFO / Debt",
    "Multichart",
    "Custom",
  ],
};
